@ECHO OFF

set NETWORK=reactive-app

docker network create %NETWORK%

docker run -d ^
    -e KAFKA_NODE_ID=0 ^
    -e KAFKA_PROCESS_ROLES=controller,broker ^
    -e KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,LOCAL://:9094 ^
    -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,LOCAL://localhost:9094 ^
    -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,LOCAL:PLAINTEXT ^
    -e KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093 ^
    -e KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER ^
    -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 ^
    -p 9094:9094 ^
    --network=%NETWORK% ^
    --name=kafka ^
    --rm ^
    apache/kafka:latest